deploy_path: "/Users/colinta/Source/GithubPages"
host: http://colinta.com
meta:
  analytics: 'UA-15076738-1'
  title: stuff by colinta
  header: colinta
  author:
    name: Colin Thomas-Arnold
    email: colinta@gmail.com
    github: https://github.com/colinta
    twitter: colinta
